server {
    listen       80;
    server_name  localhost; # your domain name

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        
        # If Nginx can't find a requested file, it sends index.html instead of a 404 error.
        # Vue Router (Single Page Applications) then handles the routing.
        try_files $uri $uri/ /index.html;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
